environment="production"
ng build @ngsf/common --configuration "$environment"
ng build @ngsf/widget-library --configuration "$environment"
ng build @ngsf/no-framework --configuration "$environment"
ng build @ngsf/bootstrap3-framework --configuration "$environment"
ng build @ngsf/bootstrap4-framework --configuration "$environment"
ng build @ngsf/bootstrap5-framework --configuration "$environment"
ng build @ngsf/material-design-framework --configuration "$environment"
ng build @ngsf/json-schema-form --configuration "$environment"
