import { Framework } from '@ngsf/common';
import { FlexLayoutRootComponent } from './components/flex-layout-root.component';
import { FlexLayoutSectionComponent } from './components/flex-layout-section.component';
import { MaterialAddReferenceComponent } from './components/material-add-reference.component';
import { MaterialButtonComponent } from './components/material-button.component';
import { MaterialButtonGroupComponent } from './components/material-button-group.component';
import { MaterialCheckboxComponent } from './components/material-checkbox.component';
import { MaterialCheckboxesComponent } from './components/material-checkboxes.component';
import { MaterialChipListComponent } from './components/material-chip-list.component';
import { MaterialDatepickerComponent } from './components/material-datepicker.component';
import { MaterialFileComponent } from './components/material-file.component';
import { MaterialInputComponent } from './components/material-input.component';
import { MaterialNumberComponent } from './components/material-number.component';
import { MaterialOneOfComponent } from './components/material-one-of.component';
import { MaterialRadiosComponent } from './components/material-radios.component';
import { MaterialSelectComponent } from './components/material-select.component';
import { MaterialSliderComponent } from './components/material-slider.component';
import { MaterialStepperComponent } from './components/material-stepper.component';
import { MaterialTabsComponent } from './components/material-tabs.component';
import { MaterialTextareaComponent } from './components/material-textarea.component';
import { MaterialDesignFrameworkComponent } from './components/material-design-framework.component';
export declare class MaterialDesignFramework extends Framework {
    name: string;
    framework: typeof MaterialDesignFrameworkComponent;
    stylesheets: string[];
    widgets: {
        root: typeof FlexLayoutRootComponent;
        section: typeof FlexLayoutSectionComponent;
        $ref: typeof MaterialAddReferenceComponent;
        button: typeof MaterialButtonComponent;
        'button-group': typeof MaterialButtonGroupComponent;
        checkbox: typeof MaterialCheckboxComponent;
        checkboxes: typeof MaterialCheckboxesComponent;
        'chip-list': typeof MaterialChipListComponent;
        date: typeof MaterialDatepickerComponent;
        file: typeof MaterialFileComponent;
        number: typeof MaterialNumberComponent;
        'one-of': typeof MaterialOneOfComponent;
        radios: typeof MaterialRadiosComponent;
        select: typeof MaterialSelectComponent;
        slider: typeof MaterialSliderComponent;
        stepper: typeof MaterialStepperComponent;
        tabs: typeof MaterialTabsComponent;
        text: typeof MaterialInputComponent;
        textarea: typeof MaterialTextareaComponent;
        'alt-date': string;
        'any-of': string;
        card: string;
        color: string;
        'expansion-panel': string;
        hidden: string;
        image: string;
        integer: string;
        radiobuttons: string;
        range: string;
        submit: string;
        tagsinput: string;
        wizard: string;
    };
}
